In [10]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.5.1+cu121
True
Tesla T4


**Creating Tensors**

In [11]:
# using empty
a = torch.empty(2,3)

In [12]:
type(a)

torch.Tensor

In [13]:
# using zeros
b = torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
# using ones
c = torch.ones(2,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
# using rand
d = torch.rand(2,3)
d

tensor([[0.4290, 0.5237, 0.5091],
        [0.2097, 0.2501, 0.2271]])

In [16]:
# manual seed
torch.manual_seed(1729)
e = torch.rand(2,3)
e

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])

In [18]:
# torch tensor
f = torch.tensor([[1,2,3],[4,5,6],[6,7,8]])
f

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [23]:
# arange
g = torch.arange(2,10,2)
g

tensor([2, 4, 6, 8])

In [25]:
# using linspace
h = torch.linspace(2,10,5)
h


tensor([ 2.,  4.,  6.,  8., 10.])

In [26]:
# using eye
i = torch.eye(3)
i

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [28]:
# using full
j = torch.full((3,3),4)
j

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

**Tensor Shape**

In [29]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
x.shape

torch.Size([3, 3])

In [31]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6066684243230141748, 3616454492322149170, 6500155724578044206],
        [7309453675965983778, 8315168162784306286, 8367752027310484831]])

In [32]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [33]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [41]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938],
        [0.6128, 0.1519, 0.0453]])

**Tensor Data Types**

In [37]:
x.dtype

torch.int64

In [38]:
torch.tensor([1.2, 4.5 ,6.7], dtype=torch.int32)

tensor([1, 4, 6], dtype=torch.int32)

In [39]:
torch.tensor([1, 4 ,6], dtype=torch.float32)

tensor([1., 4., 6.])

In [40]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])